'use client';
import { Icon } from './Icon';
import { useAccessSession } from './AccessContext';
import styles from './PasskeyAuth.module.css';

export default function PasskeyAuth({ variant = 'button', agentId = '1' }: { variant?: 'header' | 'hero' | 'button'; agentId?: string }) {
  const session = useAccessSession();
  if (variant === 'header') return <button type="button" className={`${styles.button} ${styles.headerButton}`} data-testid="header-passkey" disabled={!session.ready} onClick={() => session.address ? session.openAccess(agentId) : session.openSignIn()}><Icon name="shield" size={17} /><span className={session.address ? styles.walletAddress : undefined}>{!session.ready ? 'Loading wallet…' : session.address ? `${session.address.slice(0, 6)}…${session.address.slice(-4)}` : <><span className={styles.headerLabel}>Connect / Sign in with Passkey</span><span className={styles.mobileLabel}>Passkey sign-in</span></>}</span></button>;
  if (variant === 'hero') return <section className={styles.hero} aria-labelledby="hero-access-title"><div className={styles.heroTop}><span className={styles.heroIcon}><Icon name="shield" size={24} /></span><span className={styles.eyebrow}>YOUR AGENT. YOUR CONTROL.</span><span className={styles.provider}>DYNAMIC</span></div><div><h2 id="hero-access-title">Try 1-Tap Passkey Delegation</h2><p>Sign in with Face ID or Touch ID on a supported device. Choose who can work for your agent, and for how long.</p></div><ol className={styles.steps} aria-label="Delegation steps"><li><span>01</span>Sign in</li><li><span>02</span>Choose executor</li><li><span>03</span>Set expiry</li></ol><button type="button" className={styles.button} disabled={!session.ready} onClick={() => session.openAccess(agentId)}><Icon name="shield" size={17} />Try passkey delegation <span className={styles.actionArrow} aria-hidden="true">↗</span></button><p className={styles.note}>First-time users set up an account. On-chain delegation requires the agent owner’s wallet approval and testnet gas.</p></section>;
  return <button type="button" className={styles.button} disabled={!session.ready} onClick={() => session.openAccess(agentId)}><Icon name="shield" size={16} />Delegate task authority</button>;
}
