'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useSnapshot } from '@/lib/queries';
import { Icon } from '@/components/Icon';
import { EmptyState, LiveStatus, Metric, Notice, PageHeading } from '@/components/Shared';
import { ShardTable } from '@/components/ShardTable';
export default function Overview() {
  const { data, error, isPending } = useSnapshot();
  const samples = data?.blockSamples || [];
  const maximum = Math.max(1, ...samples.map((sample) => sample.transactions));
  const value = (input: string | number | null | undefined) => input == null ? isPending ? '—' : 'Unavailable' : Number(input).toLocaleString();
  return <>
    <PageHeading eyebrow="THE COORDINATION LAYER" title="A clear view of every agent." description="Observe your agents, follow their work, and keep every execution isolated."><LiveStatus /></PageHeading>
    {error && <Notice error>{error.message} <button className="inline-button" onClick={() => window.location.reload()}>Retry connection</button></Notice>}
    {data?.errors.map((message) => <Notice error key={message}>{message}</Notice>)}
    <section className="hero-panel"><div className="hero-copy"><span className="tag tag-cyan">BUILT FOR PARALLEL EXECUTION</span><h2>Independent agents.<br /><span>One coordinated network.</span></h2><p>Give every task its own state. Aetheris brings agent identity, isolated execution, and verifiable output together on Monad.</p><Link className="button button-primary" href="/visualizer">Explore execution <Icon name="arrow" size={17} /></Link></div><div className="architecture-art" aria-label="Architecture: tasks are routed to independent state shards"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="art-core"><Image src="/brand/aetheris-logo.svg" alt="" aria-hidden="true" width={58} height={58} /><small>AETHERIS</small></div><div className="art-node node-one"><Icon name="layers" />STATE 01</div><div className="art-node node-two"><Icon name="layers" />STATE 02</div><div className="art-node node-three"><Icon name="layers" />STATE 03</div><div className="art-caption">ISOLATION ARCHITECTURE</div></div></section>
    <section className="metric-grid" aria-label="Network metrics"><Metric title="Active agents" value={value(data?.activeAgents)} detail="Agents executing in the observed block window" icon="agents" /><Metric title="State collisions saved" value="Unavailable" detail="Monad does not expose collision telemetry" icon="shield" /><Metric title="Observed Monad TPS" value={data?.tps == null ? value(null) : data.tps.toLocaleString(undefined, { maximumFractionDigits: 1 })} detail={data?.sampleSeconds ? `Transactions / second · ${data.sampleSeconds}s sample` : 'Computed from recent block transactions'} icon="activity" accent /><Metric title="Registered identities" value={value(data?.registeredAgents)} detail="ERC-8004 identities in your registry" icon="layers" /></section>
    <div className="overview-grid"><section className="panel throughput-panel"><div className="panel-heading"><div><h2>Network throughput</h2><p>Transaction count per sampled block</p></div><span className="tag">MONAD TESTNET</span></div><div className="chart"><div className="chart-grid" /><div className="chart-bars">{samples.length ? samples.map((sample) => <div className="chart-bar-slot" key={sample.block}><div className="chart-bar" style={{ height: `${Math.max(1, sample.transactions / maximum * 100)}%` }} title={`Block ${sample.block}: ${sample.transactions} transactions`} /><span>{sample.block.slice(-3)}</span></div>) : <p className="chart-waiting">{error ? 'Network data unavailable' : 'Waiting for block samples…'}</p>}</div></div><div className="chart-footer"><span><span className="dot cyan" /> Transactions observed onchain</span><span>Recent {samples.length || '—'} blocks</span></div></section><section className="panel protocol-panel"><div className="panel-heading"><div><h2>Protocol overview</h2><p>From identity to verified output</p></div><Icon name="shield" /></div><div className="protocol-step"><span>01</span><div><h3>Discover</h3><p>ERC-8004 identities & IPFS Agent Cards</p></div></div><div className="protocol-step"><span>02</span><div><h3>Isolate</h3><p>Deterministic CREATE2 state for every task</p></div></div><div className="protocol-step"><span>03</span><div><h3>Verify</h3><p>Output commitments & Merkle settlement</p></div></div><Link className="protocol-link" href="/agents">Meet your agent network <Icon name="arrow" size={16} /></Link></section></div>
    <section className="panel"><div className="panel-heading"><div><h2>Recent task activity <span className="count-badge">{data?.eventsAvailable ? data.shards.length : '—'}</span></h2><p>{data ? `Observed blocks ${Number(data.fromBlock).toLocaleString()} – ${Number(data.blockNumber).toLocaleString()}` : 'Live creation and execution events'}</p></div><Link className="text-link" href="/visualizer">Open visualizer <Icon name="arrow" size={15} /></Link></div>{isPending ? <div className="loading-bar" role="status">Reading onchain activity…</div> : (error && !data) || (data?.routerConfigured && !data.eventsAvailable) ? <EmptyState title="Activity unavailable" description="The network could not be reached. Refresh the connection to retry." /> : <ShardTable shards={data?.shards.slice(0, 6) || []} configured={data?.routerConfigured || false} />}</section>
  </>;
}
