'use client';
import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useAgents } from '@/lib/queries';
import { contracts, explorerAddress, truncate } from '@/lib/contracts';
import { Icon } from '@/components/Icon';
import { EmptyState, Notice, PageHeading } from '@/components/Shared';
import FeaturedAgent from '@/components/FeaturedAgent';
import { SourceNotice } from '@/components/IndexedData';
import Tooltip, { glossary } from '@/components/Tooltip';
export default function Agents() {
  const [page, setPage] = useState(0);
  const [search, setSearch] = useState('');
  const queryClient = useQueryClient();
  const { data, isPending, error, refetch, isFetching } = useAgents(page);
  const agents = data?.agents.filter((agent) => `${agent.id} ${agent.name} ${agent.capabilities.join(' ')}`.toLowerCase().includes(search.toLowerCase())) || [];
  return <><PageHeading eyebrow="THE AGENT NETWORK" title="Real agents. Verifiable identities." description="Meet the Monad Observer, inspect its digital passport, and give it a task."><span className="directory-count"><Icon name="agents" />{data?.total ?? '—'} <Tooltip content={glossary.identity}>registered identities</Tooltip></span></PageHeading>
    <FeaturedAgent />
    <div className="directory-toolbar"><label className="search-input"><Icon name="search" size={18} /><input aria-label="Search agents on this page" placeholder="Search this page by name, ID, or capability…" value={search} onChange={(event) => setSearch(event.target.value)} /></label><button className="button" disabled={isFetching} onClick={() => { void refetch(); if (page !== 0) void queryClient.invalidateQueries({ queryKey: ['agents', 0] }); }}><Icon name="refresh" size={16} /> Refresh directory</button></div>
    {error && <Notice error>{error.message}</Notice>}{data?.errors.map((message) => <Notice error key={message}>{message}</Notice>)}
    <SourceNotice source={data?.source} />
    {isPending ? <div className="agent-grid" aria-label="Loading agent directory" aria-busy="true">{Array.from({ length: 6 }, (_, index) => <div className="agent-card skeleton" key={index}><div /><div /><div /></div>)}</div> : agents.length ? <section className="agent-grid">{agents.map((agent) => <article className="agent-card" key={agent.id}><div className="agent-card-top"><div className="agent-avatar"><Icon name="agents" size={25} /></div><Tooltip content={glossary.identity} label={`Explain agent ${agent.id} identity`}><span className="tag">ERC-8004 #{agent.id}</span></Tooltip></div><h2>{agent.name}</h2>{agent.tasksCompleted !== undefined && <p className="card-warning">{agent.tasksCompleted} indexed task completions</p>}<a className="owner-address mono" href={explorerAddress(agent.owner)} target="_blank" rel="noreferrer">{truncate(agent.owner)} ↗</a><p className="agent-description">{agent.description || agent.metadataError || 'This agent has not provided a description.'}</p><div className="capability-tags">{agent.capabilities.length ? agent.capabilities.map((capability) => <span key={capability}>{capability}</span>) : <span className="no-capabilities">No capabilities published</span>}</div><div className="agent-reputation"><div><span className="muted-text"><Tooltip content="The average of feedback tagged quality. Reviews are uncurated, so this is not a percentage or a guarantee of trustworthiness.">Quality score</Tooltip></span><strong>{agent.score ?? 'Unrated'}{agent.score !== null && <small> mean</small>}</strong></div><div><span className="muted-text">Feedback</span><strong>{agent.feedbackCount ?? '—'}</strong></div></div>{agent.reputationError && <p className="card-warning">{agent.reputationError}</p>}<details className="agent-endpoints"><summary>Agent Card & service endpoints <span>+</span></summary><p className="mono break-anywhere">{agent.uri || 'No Agent Card URI'}</p>{agent.endpoints.map((endpoint, index) => <div key={`${endpoint.name}-${index}`}><b>{endpoint.name}</b><code>{endpoint.endpoint}</code></div>)}</details></article>)}</section> : <section className="panel"><EmptyState title={error ? 'Directory unavailable' : search ? 'No agents match your search' : 'Your agent network starts here'} description={error ? 'Connect your deployed identity registry to load live Agent Cards.' : search ? 'Try a different name, ID, or capability on this page.' : 'Register an ERC-8004 identity to make its capabilities and endpoints discoverable.'} /></section>}
    <div className="pagination"><p>Quality scores use feedback tagged <code>quality</code>. {contracts.reputation ? 'Onchain feedback is uncurated.' : 'No reputation registry configured.'}</p><div><button className="button button-small" disabled={page === 0 || isFetching} onClick={() => { setPage(page - 1); setSearch(''); }}>Previous</button><span>Page {page + 1}</span><button className="button button-small" disabled={!data || BigInt((page + 1) * data.pageSize) >= BigInt(data.total) || isFetching} onClick={() => { setPage(page + 1); setSearch(''); }}>Next</button></div></div>
  </>;
}
